---
title: "Unraveling Tornado Trends"
subtitle: "INFO 526 - Project 1"
author: "Aes-thetics-Squad"
format: html
editor: visual
---

## Abstract

This data visualization project centers on unraveling patterns in tornado occurrences and their impacts across the United States. Tornadoes are violent, rotating columns of air that form severe thunderstorms capable of producing destructive winds. In this project we delve into two critical aspects: tornado magnitude patterns and the tornado related fatalities in each state . Through innovative visualizations like alley maps and horizontal bar plot, we seek to provide a clearer understanding of tornado phenomena, enabling informed decision-making and proactive disaster management.

## Introduction

This tornadoes data comes from NOAA's National Weather Service Storm Prediction Center [Severe Weather Maps, Graphics, and Data Page](https://www.spc.noaa.gov/wcm/#data). It is also available on the tidytuesday github page. The data has 68,693 rows and 27 columns, including numerical and categorical variables. It equips us with a treasure trove of information spanning over seven decades that is from 1950 to 2022.

To gain a deeper understanding of these tornadoes, we delve into this data containing variables such as 'magnitude'- the magnitude of tornadoes , 'state' -the state in which the tornado occurred, 'fatalities'-number of deaths for each tornado, 'year'- the year in which the tornado occurred, 'slat'- starting latitude, 'slon'-starting longitude, 'elat'- ending latitude, 'elon' - ending longtitude.

## Question 1: Are there any patterns in the magnitude of tornadoes based on location or time of year?

### Introduction

Understanding the variations in tornado intensity is vital for assessing their potential impact and devising effective disaster response plans. In this section, we explore the patterns in tornado magnitude concerning geographical location (states) and how they fluctuate across different times of the year. By examining these patterns, we aim to uncover insights that can aid in predicting and preparing for tornadoes of varying intensities, contributing to enhanced public safety and disaster management.

### Approach

Understanding the dynamics of tornado magnitude is critical for assessing the severity of these natural disasters. In our analysis, we utilize essential variables such as tornado magnitude, states, and years. By focusing on these parameters, we aim to uncover patterns in tornado intensity across various states and seasons. To visualize these patterns, we employ geospatial visualization techniques, plotting the tornado magnitudes on a US map. Specifically, we select five states that exhibit high magnitude variations and plot tornado intensity for each of these states. Through these plots, we aim to identify distinct trends in tornado magnitude, allowing for a deeper understanding of how tornadoes manifest in these states.

Tornado intensity can vary significantly across geographical regions and throughout the year. To delve deeper, we analyze the tornado data with a focus on the Enhanced Fujita (EF) scale, examining how the scale manifests concerning state-level occurrences and seasonal fluctuations. By observing the patterns in tornado intensity and their geographic spread, we can derive insights into the regions most susceptible to severe tornadoes. This multifaceted approach aims to uncover valuable insights into tornado behaviors and their potential implications for disaster preparedness and response strategies.

## Question 2: Analyzing the trends in fatalities in different states

### Introduction

Tornadoes, besides causing property damage, often result in injuries and fatalities, making an analysis of their impact crucial. In this section, we focus on understanding the trends in fatalities caused by tornadoes across various states in the United States. To address this query, it is essential to focus on specific components of the dataset, such as the year, state, and fatality counts.

Firstly, understanding how fatality rates have changed over time provides crucial insights into the effectiveness of disaster preparedness and response efforts. It helps in evaluating the impact of various safety measures and policies implemented over the years. Additionally, as climate patterns continue to shift, studying these trends can offer valuable information for adapting strategies to mitigate the human toll of tornadoes in the future. Ultimately, this analysis holds the potential to save lives and enhance the resilience of communities in the face of these natural disasters.

### Approach

To address the question regarding trends in tornado-related fatalities, we employed an area plot and a bar plot. Firstly, we utilized a area plot to visualize the general trend in the total number of fatalities over the years from 1950 to 2022. An area chart provides an effective representation of cumulative or aggregated data over a continuous range, making it ideal for showcasing trends and variations in a data over time. It allows us to observe the cumulative total of fatalities increasing over the years. Each point on the chart represents the cumulative sum of fatalities up to a specific year, providing a clear visual indication of how the fatality count has evolved.

From the area chart we saw that there are 2 peaks in the years 1953 and 2011. So, we employed a bar plot to investigate the total fatalities for those years in each state. The horizontal bar chart excels at facilitating comparisons between different categories, which in this case, are the individual states. Each bar on the chart corresponds to a specific state. The length of each bar directly corresponds to the number of fatalities, longer bars signify higher fatality counts, allowing viewers to readily grasp the relative impact of tornado-related incidents across different states

### Analysis

```{{r setup,warning=FALSE, message=FALSE, output=FALSE}}

if(!require(pacman))

  install.packages("pacman")

pacman::p_load(ggplot2,dplyr)

#suppress warning

knitr::opts_chunk$set(warning = FALSE, message = FALSE)
``

```{{r loading data}}
tornadoes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-16/tornados.csv', show_col_types = FALSE)
tornadoes <- na.omit(tornadoes)
head(tornadoes)
```

```{{r data wrangling,message=FALSE,warning=FALSE}}
#creating new column called state name
state_mapping <- setNames(state.name, state.abb)

# Add a new column "state_name" to the tornadoes dataset
tornadoes$state_name <- state_mapping[tornadoes$st]

# View the modified dataset
head(tornadoes)
```

```{{r area plot, message=FALSE, warning=FALSE}}
total_fatalities <- aggregate(fat ~ yr, data = tornadoes, sum)

# Create the area plot
ggplot(total_fatalities, aes(x = yr, y = fat)) +
  geom_area(fill="#8B0000")+
  geom_line(color="#8B0000") +
  labs(title = "Total Fatalities Over the Years",
       x = "Year",
       y = "Total Fatalities") +
   scale_x_continuous(
    breaks = seq(1950, 2022, by = 10),
    limits = c(1950, 2022))+
  theme_minimal()+
  annotate("text",x=1955,y=500, label= "1953", color = '#8B0000',
           size = 4)+
  annotate("text",x=2014,y=510, label= "2011", color = '#8B0000',
           size = 4)
```

```{{r bar plot, message=FALSE, warning=FALSE}}
total_fatalities <- tornadoes |>
  filter(yr %in% c(1953,2011))|>
  aggregate(fat ~ state_name, sum) |>
  arrange(desc(fat)) |>
  filter(fat>0)
  

# Create the bar plot
ggplot(total_fatalities, aes(x = reorder(state_name, fat), y = fat)) +
  geom_bar(stat="identity",fill="#8B0000") +
  geom_text(aes(label=fat), vjust=0.2,hjust=0,size=3) +
  coord_flip()+
   labs(x=NULL,
        y=NULL,
        title = "Total fatalities",
        subtitle="In the years 1953 and 2011",
        caption = "States not listed didnot record any deaths by tornadoes")+
  theme_minimal()+
    theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_blank()
  )
```

### Discussion

In the given analysis, we observe notable trends in tornado-related fatalities over the years. The area plot depicting total fatalities over the years shows a fluctuating pattern, with peaks and valleys in different periods. There was a peak in the year 1953 resulting in a total of almost 500 deaths in that year. After this they were random peaks and troughs from 1960's to 2010 . There was another noticeable increase in fatalities, with a peak in 2011, it is similar to the peak that occurred in 1953. In recent years, from the mid-2010s, there seems to be a slight uptick in fatalities.

The horizontal bar chart illustrates the total fatalities for select years (1953 and 2011) both years combined across various states. It reveals significant disparities in fatality counts, with some states experiencing much higher casualties than others. For instance, Alabama, Missouri and Texas are the top 3 states that has the highest death counts.

These trends may be influenced by various factors, including local infrastructure, disaster preparedness, and population density. Additionally, meteorological conditions and geographical features could play a role in the frequency and severity of tornado events in different states. Further studies could delve into these potential drivers to provide a more comprehensive understanding of the observed trends.
